"""create initial moneygraph tables

Revision ID: 28fe255db73e
Revises: 
Create Date: 2026-09-23 14:44:20.609724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fe255db73e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('n_nodes', sa.Integer(), nullable=False),
    sa.Column('n_seed', sa.Integer(), nullable=False),
    sa.Column('sum_kzt_internal', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('top_gids', sa.ARRAY(sa.String(length=32)).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('n_nodes >= 0', name=op.f('ck_clusters_n_nodes_nonnegative')),
    sa.CheckConstraint('n_seed >= 0 AND n_seed <= n_nodes', name=op.f('ck_clusters_n_seed_range')),
    sa.CheckConstraint('sum_kzt_internal >= 0', name=op.f('ck_clusters_sum_kzt_internal_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters')),
    sa.UniqueConstraint('cluster_id', name=op.f('uq_clusters_cluster_id'))
    )
    op.create_table('nodes',
    sa.Column('gid', sa.String(length=32), nullable=False),
    sa.Column('depth', sa.SmallInteger(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('depth BETWEEN 0 AND 4', name=op.f('ck_nodes_depth_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes')),
    sa.UniqueConstraint('gid', name=op.f('uq_nodes_gid'))
    )
    op.create_table('edges',
    sa.Column('src', sa.String(length=32), nullable=False),
    sa.Column('dst', sa.String(length=32), nullable=False),
    sa.Column('sum_kzt', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('n_tx', sa.Integer(), nullable=False),
    sa.Column('depth', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('depth BETWEEN 1 AND 4', name=op.f('ck_edges_depth_range')),
    sa.CheckConstraint('n_tx > 0', name=op.f('ck_edges_n_tx_positive')),
    sa.CheckConstraint('sum_kzt >= 0', name=op.f('ck_edges_sum_kzt_nonnegative')),
    sa.ForeignKeyConstraint(['dst'], ['nodes.gid'], name=op.f('fk_edges_dst_nodes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['src'], ['nodes.gid'], name=op.f('fk_edges_src_nodes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edges')),
    sa.UniqueConstraint('src', 'dst', name='uq_edges_src_dst')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edges_dst'), ['dst'], unique=False)

    op.create_table('node_assessments',
    sa.Column('gid', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('consolidator', 'transit', 'distributor', 'terminal', 'coordinator', 'peripheral', name='node_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('role_score', sa.Float(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.String(length=200), nullable=False),
    sa.Column('in_deg', sa.Integer(), nullable=False),
    sa.Column('out_deg', sa.Integer(), nullable=False),
    sa.Column('in_tx', sa.Integer(), nullable=False),
    sa.Column('out_tx', sa.Integer(), nullable=False),
    sa.Column('in_kzt', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('out_kzt', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pagerank', sa.Float(), nullable=False),
    sa.Column('pass_through', sa.Float(), nullable=True),
    sa.Column('truncated_by_depth', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('in_deg >= 0 AND out_deg >= 0', name=op.f('ck_node_assessments_degrees_nonnegative')),
    sa.CheckConstraint('in_kzt >= 0 AND out_kzt >= 0', name=op.f('ck_node_assessments_amounts_nonnegative')),
    sa.CheckConstraint('in_tx >= 0 AND out_tx >= 0', name=op.f('ck_node_assessments_tx_counts_nonnegative')),
    sa.CheckConstraint('length(evidence) <= 200', name=op.f('ck_node_assessments_evidence_length')),
    sa.CheckConstraint('pagerank >= 0', name=op.f('ck_node_assessments_pagerank_nonnegative')),
    sa.CheckConstraint('pass_through IS NULL OR pass_through >= 0', name=op.f('ck_node_assessments_pass_through_nonnegative')),
    sa.CheckConstraint('priority_score BETWEEN 0 AND 1', name=op.f('ck_node_assessments_priority_score_range')),
    sa.CheckConstraint('role_score BETWEEN 0 AND 1', name=op.f('ck_node_assessments_role_score_range')),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.cluster_id'], name=op.f('fk_node_assessments_cluster_id_clusters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gid'], ['nodes.gid'], name=op.f('fk_node_assessments_gid_nodes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_assessments')),
    sa.UniqueConstraint('gid', name=op.f('uq_node_assessments_gid'))
    )
    with op.batch_alter_table('node_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_assessments_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_assessments_priority_score'), ['priority_score'], unique=False)

    op.create_table('ranked_nodes',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('gid', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('consolidator', 'transit', 'distributor', 'terminal', 'coordinator', 'peripheral', name='node_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('priority_score BETWEEN 0 AND 1', name=op.f('ck_ranked_nodes_priority_score_range')),
    sa.CheckConstraint('rank >= 1', name=op.f('ck_ranked_nodes_rank_positive')),
    sa.ForeignKeyConstraint(['gid'], ['nodes.gid'], name=op.f('fk_ranked_nodes_gid_nodes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranked_nodes')),
    sa.UniqueConstraint('gid', name=op.f('uq_ranked_nodes_gid')),
    sa.UniqueConstraint('rank', name=op.f('uq_ranked_nodes_rank'))
    )
    op.create_table('transactions',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=32), nullable=False),
    sa.Column('dst', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sum_kzt', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('row_id >= 0', name=op.f('ck_transactions_row_id_nonnegative')),
    sa.CheckConstraint('sum_kzt >= 0', name=op.f('ck_transactions_sum_kzt_nonnegative')),
    sa.ForeignKeyConstraint(['dst'], ['nodes.gid'], name=op.f('fk_transactions_dst_nodes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['src', 'dst'], ['edges.src', 'edges.dst'], name='fk_transactions_src_dst_edges', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['src'], ['nodes.gid'], name=op.f('fk_transactions_src_nodes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('row_id', name=op.f('uq_transactions_row_id'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_dst'), ['dst'], unique=False)
        batch_op.create_index('ix_transactions_src_dst', ['src', 'dst'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_src_dst')
        batch_op.drop_index(batch_op.f('ix_transactions_dst'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))

    op.drop_table('transactions')
    op.drop_table('ranked_nodes')
    with op.batch_alter_table('node_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_assessments_priority_score'))
        batch_op.drop_index(batch_op.f('ix_node_assessments_cluster_id'))

    op.drop_table('node_assessments')
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edges_dst'))

    op.drop_table('edges')
    op.drop_table('nodes')
    op.drop_table('clusters')
    # ### end Alembic commands ###
